services:
  web:
    build:
      context: ./wedotv_ott_back
      dockerfile: ./.docker/Dockerfile.dev
    volumes:
      - './wedotv_ott_back/.env:/var/www/html/.env'
      - './wedotv_ott_back:/app'
      - 'caddy_data:/data'
      - 'caddy_config:/config'
    tty: true
    ports:
      - '80:80'
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql:
  caddy_data:
  caddy_config: